language: node_js
node_js:
  - "8"

env:
  global:
  - GH_REF=github.com/MissingMaps/leaderboards
  - DEPLOY_BRANCH=master

cache:
  directories:
    - node_modules

script:
- npm run build

after_success:
- ./.build_scripts/deploy.sh
